page:
  baseurl: /
  name: Jux Site
  description: Non enim vos estis
  lang: en
  direction: ltr
defaults:
  env: development
  debug: false
  publictheme: public_theme
  admintheme: admin_theme
layouts:
  admin:
    position-01:
    - f
    maincontent:
    - dashboard
  public:
    maincontent:
    - article
    position-03:
    - article_menu_categories
    - article_menu_articles